const TOKEN_TTL_SECONDS = 60 * 60 * 24 * 7;
function getSecret(){const secret=process.env.ADMIN_JWT_SECRET;if(!secret||secret.length<32)throw new Error("ADMIN_JWT_SECRET must be set and contain at least 32 characters.");return new TextEncoder().encode(secret);}
function enc(value:string){return btoa(value).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
function dec(value:string){return atob(value.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(value.length/4)*4,"="));}
async function sign(input:string){const key=await crypto.subtle.importKey("raw",getSecret(),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(input));let binary="";new Uint8Array(sig).forEach(b=>binary+=String.fromCharCode(b));return enc(binary);}
async function verifySignature(input:string,signature:string){const key=await crypto.subtle.importKey("raw",getSecret(),{name:"HMAC",hash:"SHA-256"},false,["verify"]);const binary=dec(signature);const bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));return crypto.subtle.verify("HMAC",key,bytes,new TextEncoder().encode(input));}
export async function createAdminToken(adminId:string,email:string){const header=enc(JSON.stringify({alg:"HS256",typ:"JWT"}));const payload=enc(JSON.stringify({sub:adminId,email,exp:Math.floor(Date.now()/1000)+TOKEN_TTL_SECONDS}));const unsigned=`${header}.${payload}`;return `${unsigned}.${await sign(unsigned)}`;}
export async function verifyAdminToken(token:string|undefined){if(!token)return null;try{const parts=token.split(".");if(parts.length!==3)return null;const [header,payload,signature]=parts;const headerData=JSON.parse(dec(header));if(headerData.alg!=="HS256"||headerData.typ!=="JWT")return null;if(!(await verifySignature(`${header}.${payload}`,signature)))return null;const data=JSON.parse(dec(payload));if(!data.sub||!data.email||typeof data.exp!=="number"||data.exp<=Math.floor(Date.now()/1000))return null;return{adminId:String(data.sub),email:String(data.email)};}catch{return null;}}
export const TOKEN_TTL=TOKEN_TTL_SECONDS;
