import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import PartnerForm from "@/components/partner/PartnerForm";
import { CheckCircle2, Link2, Users, Wallet, TrendingUp, ShieldCheck } from "lucide-react";
export const metadata = { title: "Become a Partner" };
const steps=[['1','Join Arvik Digital','Submit your partner application and let us review your profile.'],['2','Get Approved','Receive your unique referral code and shareable referral link.'],['3','Refer Clients','Send genuine businesses and clients who need our digital services.'],['4','Earn 20%','Earn commission on successful projects after client payment is received.']];
const packages=[['Static Website','₹6,500','₹1,300'],['Business Website','₹8,000','₹1,600'],['Professional Website','₹14,000','₹2,800']];
export default function BecomePartnerPage(){return <><Navbar/><main className="min-h-screen overflow-hidden bg-[#070707] pt-20 text-white"><section className="relative border-b border-yellow-400/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(234,179,8,.18),transparent_30%),radial-gradient(circle_at_80%_30%,rgba(234,179,8,.08),transparent_28%)]"/><div className="container relative grid gap-12 py-20 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-28"><div><div className="inline-flex rounded-full border border-yellow-400/30 bg-yellow-400/10 px-4 py-2 text-sm font-bold text-yellow-200">🤝 ARVIK DIGITAL PARTNER PROGRAM</div><h1 className="mt-6 text-5xl font-black leading-[.95] md:text-7xl">REFER.<br/><span className="text-yellow-300">EARN.</span><br/>GROW TOGETHER.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-zinc-300">Partner with Arvik Digital, refer genuine clients, and earn <strong className="text-yellow-300">20% commission</strong> on every successful project.</p><div className="mt-8 flex flex-wrap gap-4"><a href="#apply" className="rounded-2xl bg-gradient-to-r from-yellow-300 to-yellow-600 px-6 py-4 font-black text-black">Become a Partner</a><a href="#how-it-works" className="rounded-2xl border border-white/15 px-6 py-4 font-bold text-white">How It Works</a></div></div><div className="grid gap-4 sm:grid-cols-2"><Card icon={<Wallet/>} title="20% Commission" text="Earn on successful projects."/><Card icon={<Link2/>} title="Unique Referral Link" text="Track your referrals easily."/><Card icon={<TrendingUp/>} title="No Earning Limit" text="More successful referrals, more earnings."/><Card icon={<ShieldCheck/>} title="Professional Support" text="We handle delivery and client service."/></div></div></section>
<section id="how-it-works" className="container py-20"><Header eyebrow="Simple process" title="How the Partner Program Works"/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{steps.map(([n,t,d])=><div key={n} className="rounded-[28px] border border-white/10 bg-white/[0.03] p-6"><span className="text-5xl font-black text-yellow-300/80">{n}</span><h3 className="mt-6 text-xl font-black">{t}</h3><p className="mt-3 leading-7 text-zinc-400">{d}</p></div>)}</div></section>
<section className="border-y border-white/10 bg-white/[0.02]"><div className="container py-20"><Header eyebrow="Your earnings" title="Example 20% Commission"/><div className="mt-10 grid gap-5 md:grid-cols-3">{packages.map(([n,p,c])=><div key={n} className="rounded-[30px] border border-yellow-400/20 bg-black/40 p-7"><p className="text-sm font-bold uppercase tracking-wider text-zinc-400">{n}</p><p className="mt-4 text-4xl font-black">{p}</p><div className="mt-6 border-t border-white/10 pt-5"><p className="text-sm text-zinc-400">Your 20% commission</p><p className="mt-1 text-3xl font-black text-yellow-300">{c}</p></div></div>)}</div><p className="mt-6 text-sm text-zinc-500">Commission is calculated on the actual amount received from the client and becomes payable after a successful paid project.</p></div></section>
<section id="apply" className="container py-20"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-start"><div><Header eyebrow="Start today" title="Ready to Grow With Us?"/><p className="mt-5 max-w-xl text-lg leading-8 text-zinc-400">Apply now. Once approved, you will receive your unique referral code for tracking successful client referrals.</p><div className="mt-8 space-y-4">{['No joining fee','20% commission on successful projects','Unique referral code','Transparent partner management'].map(x=><div key={x} className="flex items-center gap-3 text-zinc-200"><CheckCircle2 className="text-yellow-300" size={20}/>{x}</div>)}</div></div><PartnerForm/></div></section></main><Footer/></>}
function Header({eyebrow,title}:{eyebrow:string;title:string}){return <div><p className="text-sm font-bold uppercase tracking-[.3em] text-yellow-300">{eyebrow}</p><h2 className="mt-3 text-4xl font-black md:text-5xl">{title}</h2></div>}
function Card({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="rounded-[26px] border border-white/10 bg-white/[0.04] p-6"><div className="text-yellow-300">{icon}</div><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-400">{text}</p></div>}
